"""initial migration

Revision ID: 7c708f1c4961
Revises: 
Create Date: 2025-07-26 23:18:39.563657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c708f1c4961'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('pregnant', sa.Boolean(), nullable=True),
    sa.Column('medical_records', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('is_lamb', sa.Boolean(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.Column('father_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['father_id'], ['sheep.id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['sheep.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id')
    )
    op.create_table('lambs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('mother_tag_id', sa.String(length=50), nullable=True),
    sa.Column('father_tag_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['father_tag_id'], ['sheep.tag_id'], ),
    sa.ForeignKeyConstraint(['mother_tag_id'], ['sheep.tag_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lambs')
    op.drop_table('sheep')
    # ### end Alembic commands ###
