"""Add weaning_weight column to sheep table

Revision ID: b8d8797146bb
Revises: 7c708f1c4961
Create Date: 2025-08-05 06:37:11.342004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d8797146bb'
down_revision = '7c708f1c4961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lambs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weaning_weight', sa.Float(), nullable=True))

    with op.batch_alter_table('sheep', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weaning_weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheep', schema=None) as batch_op:
        batch_op.drop_column('weaning_weight')

    with op.batch_alter_table('lambs', schema=None) as batch_op:
        batch_op.drop_column('weaning_weight')

    # ### end Alembic commands ###
